apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: kubeflow
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data  # Adjust for your cluster's storage backend