apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
  namespace: kubeflow
spec:
  capacity:
    storage: 50Gi  # Adjust based on LLaVA 7B model size
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/model  # Adjust for your cluster's storage backend